uploads = []
generated = []

[[outputs]]
id = "R8UheHFt932b60zFGm3q3"
uri = "file://grupo-vip-netlify.zip"
type = "unspecified"
title = "grupo-vip-netlify.zip — Build atualizado com Meta Pixel"

[[outputs]]
id = "BP6JgCzxAB-AaN-P1k64e"
uri = "file://grupo-vip-netlify.tar.gz"
type = "unspecified"
title = "Grupo VIP — Build Atualizada (VSL corrigida)"
